apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/AkiraTomori/DevOps-YAS.git'
    targetRevision: main  # Co dinh theo nhanh hoac tag cu the, khong dung wildcard
    path: k8s/env-staging # Thu muc chua cau hinh staging
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: staging        # Tự động deploy vào namespace staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true