apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-config-staging
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/AkiraTomori/DevOps-YAS.git
    targetRevision: main
    path: k8s/charts/yas-configuration
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cart-staging
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/AkiraTomori/DevOps-YAS.git
    targetRevision: main
    path: k8s/charts/cart
    helm:
      values: |
        backend:
          image:
            tag: latest
          service:
            type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: customer-staging
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/AkiraTomori/DevOps-YAS.git
    targetRevision: main
    path: k8s/charts/customer
    helm:
      values: |
        backend:
          image:
            tag: latest
          service:
            type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inventory-staging
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/AkiraTomori/DevOps-YAS.git
    targetRevision: main
    path: k8s/charts/inventory
    helm:
      values: |
        backend:
          image:
            tag: latest
          service:
            type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: location-staging
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/AkiraTomori/DevOps-YAS.git
    targetRevision: main
    path: k8s/charts/location
    helm:
      values: |
        backend:
          image:
            tag: latest
          service:
            type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media-staging
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/AkiraTomori/DevOps-YAS.git
    targetRevision: main
    path: k8s/charts/media
    helm:
      values: |
        backend:
          image:
            tag: latest
          service:
            type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order-staging
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/AkiraTomori/DevOps-YAS.git
    targetRevision: main
    path: k8s/charts/order
    helm:
      values: |
        backend:
          image:
            tag: latest
          service:
            type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product-staging
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/AkiraTomori/DevOps-YAS.git
    targetRevision: main
    path: k8s/charts/product
    helm:
      values: |
        backend:
          image:
            tag: latest
          service:
            type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rating-staging
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/AkiraTomori/DevOps-YAS.git
    targetRevision: main
    path: k8s/charts/rating
    helm:
      values: |
        backend:
          image:
            tag: latest
          service:
            type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: search-staging
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/AkiraTomori/DevOps-YAS.git
    targetRevision: main
    path: k8s/charts/search
    helm:
      values: |
        backend:
          image:
            tag: latest
          service:
            type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tax-staging
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/AkiraTomori/DevOps-YAS.git
    targetRevision: main
    path: k8s/charts/tax
    helm:
      values: |
        backend:
          image:
            tag: latest
          service:
            type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
